spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: admin-cli
      principle-attribute: preferred_username

keycloack:
  realm: myrealm
  grant-type: password
  client-id: admin-cli
  client-secret: 3AlxlutPKMpYon2PxwbWGU9jj729G19A
  username: ali
  password: 1234
  ipAddress: http://localhost:8080
  endpoints:
    token: ${keycloack.ipAddress}/realms/${keycloack.realm}/protocol/openid-connect/token
    userInfo: ${keycloack.ipAddress}/realms/${keycloack.realm}/protocol/openid-connect/userinfo
    users:
